### ISSUE TITLE
HSBCG - Sporadic API Request Issues - 504 Endpoint Request Timed Out

### ISSUE THREAD

**Issue by tobypinder** [openbankingspace/tpp-issues#12]
Working with HSBCG to discover the source of some sporadic `504` errors being returned from Resource Endpoints with the payload

```js
{"message": "Endpoint request timed out"}
```

Retry mechanisms usually render these benign, and subsequent retries of the same call are usually successful.

**Comment by jspaine** [comment]
We're also seeing 504's from the `token` endpoint. With the `refresh_token` grant this results in the refresh token being invalidated even though we don't receive the new tokens, and users being required to reauthorise.

I wasn't sure if this should be a different issue because of the severity.

**Issue**: OBSD-4358
**Reported**: 1st Aug 18

**Comment by tobypinder** [comment]
@jspaine I think the "refresh_token endpoint failure == lockout" issue is very distinct from the overall instability - ASPSPs should expect to have some level of request failure and this kind of scenario must be recoverable for the TPP imho

**Comment by jspaine** [comment]
True, I'll make it a new issue.

**Comment by tobypinder** [comment]
Appears to be resolved as of the Version 2 APIs - we've closed the issue on OBSD and continue to monitor reliability and performance.
